apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: demo
    function: slow-cooker
  name: slow-cooker
  namespace: demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: demo
      function: slow-cooker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo
        function: slow-cooker
    spec:
      containers:
      - args: ["--qps", "100", "--concurrency", "10", "http://poc-ui.demo:8080/api/places/?query=San+Diego&include=weather"]
        image: buoyantio/slow_cooker:d76405f51d77
        imagePullPolicy: IfNotPresent
        name: slow-cooker
        resources:
          requests:
            cpu: 100m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
