apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: poc-ui
      component: demo
    name: poc-ui
    selfLink: /api/v1/namespaces/demo/services/poc-ui
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: poc-ui
      component: demo
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: maps
      component: demo
    name: maps-service
    selfLink: /api/v1/namespaces/demo/services/maps-service
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: maps
      component: demo
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
