apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: weather
    component: demo
  name: weather
  namespace: demo
  selfLink: /apis/extensions/v1beta1/namespaces/demo/deployments/weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
      component: demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: weather
        component: demo
    spec:
      containers:
      - env:
        - name: WUNDERGROUND_KEY
          valueFrom:
            secretKeyRef:
              name: wunderground-service-secret
              key: WUNDERGROUND_KEY
        - name: WUNDERGROUND_URL
          value: https://api.darksky.net/forecast/%v
        - name: WUNDERGROUND_FORECAST_PATH
          value: /%v,%v
        image: cpretzer/wunderground-service:0.1.2
        imagePullPolicy: Always
        name: weather
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: 
          limits:
            memory: 100Mi
            cpu: 250m
          requests:
            memory: 50Mi
            cpu: 100m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: docker-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
