apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: weather
    component: demo
  name: weather
  selfLink: /apis/extensions/v1beta1/namespaces/demo/deployments/weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
      component: demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: weather
        component: demo
    spec:
      containers:
      - env:
        - name: WUNDERGROUND_KEY
            valueFrom:
              secretKeyRef:
                name: wunderground-service-secret
                key: WUNDERGROUND_KEY
        - name: WUNDERGROUND_URL
          value: https://api.wunderground.com/api/%v
        - name: WUNDERGROUND_FORECAST_PATH
          value: /forecast/q/%v,%v/json
        image: cpretzer/wunderground-service:demo
        imagePullPolicy: Always
        name: weather
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: docker-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
